baud: '115200'
controllers: {}
joints:
  lf_coxa_bone_joint:
    id: 9
    inverted: true
    max_angle: 2.29074464324
    max_speed: 100.0
    min_angle: -2.31119772041
    readable: true
    type: dynamixel
  lf_femur_bone_joint:
    id: 10
    inverted: false
    max_angle: 1.72828502102
    max_speed: 100.0
    min_angle: -1.78964425253
    readable: true
    type: dynamixel
  lf_tibia_bone_joint:
    id: 11
    inverted: true
    max_angle: 2.443
    max_speed: 100.0
    min_angle: -2.443
    readable: true
    type: dynamixel
  lr_coxa_bone_joint:
    id: 13
    inverted: false
    max_angle: 2.29074464324
    max_speed: 100.0
    min_angle: -2.31119772041
    readable: true
    type: dynamixel
  lr_femur_bone_joint:
    id: 14
    inverted: false
    max_angle: 1.72828502102
    max_speed: 100.0
    min_angle: -1.78964425253
    readable: true
    type: dynamixel
  lr_tibia_bone_joint:
    id: 15
    inverted: true
    max_angle: 2.443
    max_speed: 100.0
    min_angle: -2.443
    readable: true
    type: dynamixel
  neck_pan_joint:
    id: 17
    inverted: false
    max_angle: 2.61799
    max_speed: 100.0
    min_angle: -2.61799
    readable: true
    type: dynamixel
  neck_tilt_joint:
    id: 18
    inverted: false
    max_angle: 1.5707
    max_speed: 100.0
    min_angle: -1.5707
    readable: true
    type: dynamixel
  rf_coxa_bone_joint:
    id: 1
    inverted: false
    max_angle: 2.29074464324
    max_speed: 100.0
    min_angle: -2.31119772041
    readable: true
    type: dynamixel
  rf_femur_bone_joint:
    id: 2
    inverted: false
    max_angle: 1.72828502102
    max_speed: 100.0
    min_angle: -1.78964425253
    readable: true
    type: dynamixel
  rf_tibia_bone_joint:
    id: 3
    inverted: true
    max_angle: 2.443
    max_speed: 100.0
    min_angle: -2.443
    readable: true
    type: dynamixel
  rr_coxa_bone_joint:
    id: 5
    inverted: true
    max_angle: 2.29074464324
    max_speed: 100.0
    min_angle: -2.31119772041
    readable: true
    type: dynamixel
  rr_femur_bone_joint:
    id: 6
    inverted: false
    max_angle: 1.72828502102
    max_speed: 100.0
    min_angle: -1.78964425253
    readable: true
    type: dynamixel
  rr_tibia_bone_joint:
    id: 7
    inverted: true
    max_angle: 2.443
    max_speed: 100.0
    min_angle: -2.443
    readable: true
    type: dynamixel
port: /dev/ttyUSB0
rate: 20.0
sim: true
sync_read: true
sync_write: true
